### ISSUE TITLE
NODE_ENV should be optional

### ISSUE THREAD

**Issue by ghost** [rei/febs#23]
`febs` should have the capability to respect the $NODE_ENV environment variable, however if one is not specified it should be able rely on the target provided, e.g.

`febs dev` & `febs prod` should properly set NODE_ENV for any spawned sub processes.

**Comment by peripateticus** [comment]
Rather than it be optional, I would want to eliminate the need completely. I actually have a branch where I was working on this. The difficulty, if I recall, is with `webpack` and getting the particular environment that you are building in to the `webpack.config` since you cannot set environment variables within `node`.

**Comment by dewilli-rei** [comment]
#95 now solves this
